# Scaled Mobs Mod
# Copyright (c) 2020 Ryan Sammons
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

modLoader="javafml"
loaderVersion="[32,)"
license="GNU General Public License version 3.0"

[[mods]]
  modId="scaledmobs"
  version="${file.jarVersion}"
  displayName="Scaled Mobs Mod"
  #updateJSONURL=""
  #displayURL=""
  #logoFile=""
  #credits=""
  authors="Ryan Sammons (TheFatDeegz)"
  description='''
Adds the ability to set the size of mobs and
change attributes based on their size. You can
use this to make certain mobs in a world a custom
size, spawn mobs with different default settings,
or even spawn randomly sized mobs!

Scaled Mobs Mod
Copyright (c) 2020 Ryan Sammons

This program is free software: you can
redistribute it and/or modify it under the terms
of the GNU General Public License as published by
the Free Software Foundation, either version 3 of
the License, or (at your option) any later
version.

This program is distributed in the hope that it
will be useful, but WITHOUT ANY WARRANTY; without
even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU
General Public License along with this program.
If not, see <https://www.gnu.org/licenses/>.
'''
  [[dependencies.scaledmobs]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[32,)" #mandatory
    ordering="NONE"
    side="BOTH"
  [[dependencies.scaledmobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
